var searchData=
[
  ['dailyfirstvaccination_1681',['DailyFirstVaccination',['../structmio_1_1osecirvvs_1_1DailyFirstVaccination.html',1,'mio::osecirvvs']]],
  ['dailyfullvaccination_1682',['DailyFullVaccination',['../structmio_1_1osecirvvs_1_1DailyFullVaccination.html',1,'mio::osecirvvs']]],
  ['damping_1683',['Damping',['../classmio_1_1Damping.html',1,'mio']]],
  ['dampingmatrixexpression_1684',['DampingMatrixExpression',['../classmio_1_1DampingMatrixExpression.html',1,'mio']]],
  ['dampingmatrixexpression_3c_20squaredampings_20_3e_1685',['DampingMatrixExpression&lt; SquareDampings &gt;',['../classmio_1_1DampingMatrixExpression.html',1,'mio']]],
  ['dampingmatrixexpression_3c_20vectordampings_20_3e_1686',['DampingMatrixExpression&lt; VectorDampings &gt;',['../classmio_1_1DampingMatrixExpression.html',1,'mio']]],
  ['dampingmatrixexpressiongroup_1687',['DampingMatrixExpressionGroup',['../classmio_1_1DampingMatrixExpressionGroup.html',1,'mio']]],
  ['dampingmatrixexpressiongroup_3c_20contactmatrix_20_3e_1688',['DampingMatrixExpressionGroup&lt; ContactMatrix &gt;',['../classmio_1_1DampingMatrixExpressionGroup.html',1,'mio']]],
  ['dampingmatrixexpressiongroup_3c_20migrationcoefficients_20_3e_1689',['DampingMatrixExpressionGroup&lt; MigrationCoefficients &gt;',['../classmio_1_1DampingMatrixExpressionGroup.html',1,'mio']]],
  ['dampings_1690',['Dampings',['../classmio_1_1Dampings.html',1,'mio']]],
  ['dampingsampling_1691',['DampingSampling',['../classmio_1_1DampingSampling.html',1,'mio']]],
  ['dataerror_1692',['DataError',['../classmemilio_1_1epidata_1_1getDataIntoPandasDataFrame_1_1DataError.html',1,'memilio::epidata::getDataIntoPandasDataFrame']]],
  ['datawritertomemory_1693',['DataWriterToMemory',['../structmio_1_1DataWriterToMemory.html',1,'mio']]],
  ['date_1694',['Date',['../structmio_1_1Date.html',1,'mio']]],
  ['daysuntileffectiveimprovedimmunity_1695',['DaysUntilEffectiveImprovedImmunity',['../structmio_1_1osecirvvs_1_1DaysUntilEffectiveImprovedImmunity.html',1,'mio::osecirvvs']]],
  ['daysuntileffectivepartialimmunity_1696',['DaysUntilEffectivePartialImmunity',['../structmio_1_1osecirvvs_1_1DaysUntilEffectivePartialImmunity.html',1,'mio::osecirvvs']]],
  ['deathspercritical_1697',['DeathsPerCritical',['../structmio_1_1osecir_1_1DeathsPerCritical.html',1,'mio::osecir::DeathsPerCritical'],['../structmio_1_1osecirvvs_1_1DeathsPerCritical.html',1,'mio::osecirvvs::DeathsPerCritical']]],
  ['dereffunctor_1698',['DerefFunctor',['../structmio_1_1details_1_1DerefFunctor.html',1,'mio::details']]],
  ['detectinfection_1699',['DetectInfection',['../structmio_1_1abm_1_1DetectInfection.html',1,'mio::abm']]],
  ['discretedistributioninplace_1700',['DiscreteDistributionInPlace',['../classmio_1_1DiscreteDistributionInPlace.html',1,'mio']]],
  ['disjunction_1701',['disjunction',['../structmio_1_1disjunction.html',1,'mio']]],
  ['disjunction_3c_20b1_20_3e_1702',['disjunction&lt; B1 &gt;',['../structmio_1_1disjunction_3_01B1_01_4.html',1,'mio']]],
  ['disjunction_3c_20b1_2c_20bn_2e_2e_2e_20_3e_1703',['disjunction&lt; B1, Bn... &gt;',['../structmio_1_1disjunction_3_01B1_00_01Bn_8_8_8_01_4.html',1,'mio']]],
  ['distributionadapter_1704',['DistributionAdapter',['../classmio_1_1DistributionAdapter.html',1,'mio']]],
  ['distributionadapter_3c_20double_20_3e_1705',['DistributionAdapter&lt; double &gt;',['../classmio_1_1DistributionAdapter.html',1,'mio']]],
  ['dots_1706',['Dots',['../classmemilio_1_1epidata_1_1progress__indicator_1_1Dots.html',1,'memilio::epidata::progress_indicator']]],
  ['dynamicnpis_1707',['DynamicNPIs',['../classmio_1_1DynamicNPIs.html',1,'mio']]],
  ['dynamicnpisinfectedsymptoms_1708',['DynamicNPIsInfectedSymptoms',['../structmio_1_1osecir_1_1DynamicNPIsInfectedSymptoms.html',1,'mio::osecir::DynamicNPIsInfectedSymptoms'],['../structmio_1_1osecirvvs_1_1DynamicNPIsInfectedSymptoms.html',1,'mio::osecirvvs::DynamicNPIsInfectedSymptoms']]]
];
