
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/jadebeck/repos/LOKI/memilio/pycode/memilio-simulation/.eggs/cmake-3.26.4-py3.10-linux-x86_64.egg/cmake/data/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:10 (project)"
    message: |
      The system is: Linux - 5.19.0-43-generic - x86_64
...
